Add github actions ci pipeline
splunk/kafka-connect-splunk pull request #286
Opened 2021-09-14 19:22 UTC by mwang2016

2021-09-16 17:01 UTC, chaitanyaphalak requested changes

2021-09-16 17:01 UTC, chaitanyaphalak commented on test/config.yaml
> +old_connector_name: splunk-kafka-connect-v1.2.0.jar
can be changed if we change the old connector version

2021-09-16 17:01 UTC, chaitanyaphalak commented on test/lib/commonkafka.py
> +        # logger.info("Deleted connector successfully - " + connector)
can be changed to debug

2021-09-16 17:08 UTC, mwang2016 commented on .github/workflows/ci_build_test.yaml
> +          - kafka_version: "2.6.0"
sure, i will add them

2021-09-16 17:08 UTC, mwang2016 commented on .github/workflows/ci_build_test.yaml
> +      CI_SPLUNK_VERSION: "8.2.0"
sure

2021-09-16 17:11 UTC, mwang2016 commented on .github/workflows/ci_build_test.yaml
> +      KUBERNETES_VERSION: v1.15.2
Yes, it was a mistake, I thought i would install splunk on kubernetes, forgot to remove it after.

2021-09-16 17:13 UTC, mwang2016 commented on .github/workflows/ci_build_test.yaml
> +      CI_OLD_CONNECTOR_VERSION: v1.2.0
It is the old version of connector that I need to use for testing upgrade. The idea is to install v1.2.0 first, start sending data and then upgrade to v2.0.2

2021-09-16 17:17 UTC, mwang2016 commented on test/lib/commonkafka.py
> +        # logger.info("Deleted connector successfully - " + connector)
yes

2021-09-17 18:05 UTC, chaitanyaphalak submitted a review, later dismissed

2021-09-17 23:19 UTC, chaitanyaphalak approved these changes

2021-09-17 23:19 UTC, merged