Add auto extract timestamp parameter support
splunk/kafka-connect-splunk pull request #415
Opened 2023-10-26 13:25 UTC by ludovic-boutros

We need to be able to enable the ["auto extract timestamp"](https://docs.splunk.com/Documentation/Splunk/9.1.1/RESTREF/RESTinput#services.2Fcollector.2Fevent) feature for a project.

This parameter is not exposed yet and therefore cannot be set on the HEC URI.

This PR expose this parameter.
It is not set by default to be keep compatibility with current behavior.

I have created a specific HEC URI builder in order to ease testing.

2023-10-29 15:25 UTC, VihasMakwana requested changes

2023-10-29 15:25 UTC, VihasMakwana commented on src/main/java/com/splunk/kafka/connect/SplunkSinkConnectorConfig.java
> +    static final String AUTO_EXTRACT_TIMESTAMP_DOC = "Sends timestamped events to HTTP Event Collector using the Splunk platform JSON event protocol when auto_extract_timestamp is set to \"true\" in
```suggestion
    static final String AUTO_EXTRACT_TIMESTAMP_DOC = "When set to true, it forces Splunk HEC to extract the timestamp from event envelope/event data";
```

2023-10-29 15:25 UTC, VihasMakwana commented on README.md
> +| `splunk.hec.auto.extract.timestamp` |  Sends timestamped events to HTTP Event Collector using the Splunk platform JSON event protocol when auto_extract_timestamp is set to `true` in the /event URL.
```suggestion
| `splunk.hec.auto.extract.timestamp` | When set to `true`, it forces Splunk HEC to extract the timestamp from the event envelope/event data. See [/services/collector/event](https://docs.splunk.com/Documentation/Splunk/9.1.1/RESTREF/RESTinput#services.2Fcollector.2Fevent) for more details | `unset`       |
```

2023-10-29 15:27 UTC, VihasMakwana commented
Looks good other than a couple of nits. Also, my CI has been failing lately so I'll merge it only after I get it green.
It might take some time. I'll approve the PR though.

Thanks for the change, @ludovic-boutros. Appreciate it!

2023-11-07 09:23 UTC, ludovic-boutros commented
@VihasMakwana It should be good now 👍 
Thank you.

2023-11-07 11:54 UTC, VihasMakwana approved these changes

2023-11-07 11:54 UTC, merged

2023-11-08 10:17 UTC, ludovic-boutros commented
Thank you @VihasMakwana. 
Any idea of next release date ?

2023-11-21 12:43 UTC, VihasMakwana commented
@ludovic-boutros Released in 2.2.0, let me know if it's good for you.

2023-11-21 18:11 UTC, ludovic-boutros commented
That's perfect, thank you 👍